Quotes/Models/Quotation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Quotes.Models
{
    public class Quotation
    {
        public virtual Category Category { get; set; }
        [DisplayName("Category")]
        public int CategoryID { get; set; }
        public int QuotationID { get; set; }
        [Required]
        public string Quote { get; set; }
        [Required]
        public string Author { get; set; }

        [DisplayFormat(DataFormatString="{0:MM/dd/yyyy}")]
        public DateTime Date { get; set; }

        public virtual ApplicationUser User { get; set; } 


        
    }
}

Quotes/Controllers/QuotationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Quotes.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Quotes.Controllers
{
    public class QuotationController : Controller
    {
        private QuotationContext db;
        private UserManager<ApplicationUser> userManager;

        public QuotationController()
        {
        db = new QuotationContext();
        userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

        }
        // GET: /Quotation/
        public ActionResult Index(string filter)
        {
            //checks if user is logged in 
            if(User.Identity.IsAuthenticated)
                  ViewBag.loggedIn = true;            
            else
                  ViewBag.loggedIn = false;

        //check if the user is an admin
            if (User.IsInRole("Admin"))
            {
                ViewBag.admin = true;
                ViewBag.UserName = new SelectList(db.Users, "UserName", "UserName");
            }
            else
            {
                ViewBag.admin = false;
                ViewBag.UserName = null;
            }

            //if the hidden cookie exists then show the unhide switch
            if (Request.Cookies.AllKeys.Contains("hidden"))
                ViewBag.ShowUnhideButton = true;            
            else
                ViewBag.ShowUnhideButton = false;      

            //initialize this so there's no null errors
            ViewBag.ShowDisplayAllButton = false;

            //Collect the hidden ids from the cookie            
            List<int> hiddenIds = new List<int>();
            if (Request.Cookies.AllKeys.Contains("hidden"))
            {
                string[] CookieIds = Request.Cookies["hidden"].Value.ToString().Split(' ');               
                //change the strings into a list of ints
                foreach (string id in CookieIds)
                {
                    int temp = int.Parse(id);
                    hiddenIds.Add(temp);
                }
            }
            var quotations = db.Quotations.Include(q => q.Category);
            //search logic that checks all quotes for the indicated filter, and doesnt show hidden quotes
            if (String.IsNullOrEmpty(filter))
            {
                ViewBag.ShowDisplayAllButton = false;
                quotations = quotations.Where(c => !hiddenIds.Contains(c.QuotationID));                    
                return View(quotations.ToList());
            }
            else
            {
                ViewBag.ShowDisplayAllButton = true;
                quotations = quotations.Where(c => !hiddenIds.Contains(c.QuotationID));  
                quotations = db.Quotations.Include(q => q.Category).Where(q => q.Category.Name.Contains(filter) || q.Quote.Contains(filter) || q.Author.Contains(filter));
                return View(quotations.ToList());
            }
            
        }


        public ActionResult HideQuote(String Id)
        {
            //if there is not already a cookie create it and add the current id
            if(!Request.Cookies.AllKeys.Contains("hidden"))
            {
                HttpCookie cookie = new HttpCookie("hidden", " " + Id);
                Response.Cookies.Add(cookie);
            }
            //if the cookie is already there add the new id to it
            else
            {
                HttpCookie cookie = Request.Cookies["hidden"];
                cookie.Value += " " + Id;
                Response.Cookies.Add(cookie);
            }
            
            return RedirectToAction("Index");
        }

        public ActionResult Unhide()
        {
            HttpCookie deleteCookie = new HttpCookie("hidden");
            deleteCookie.Expires = DateTime.Now.AddHours(-1);
            Response.Cookies.Add(deleteCookie);
            return RedirectToAction("Index");
        }

        public ActionResult userQuotes(string UserName)
        {

            ViewBag.userList = db.Users;
            if (String.IsNullOrEmpty(UserName))
            {
                var userid = User.Identity.GetUserId();
                var quotations = db.Quotations.Include(q => q.Category);
                quotations = quotations.Where(q => q.User.Id == userid);
                return View(quotations);
            }

            else
            {
                if (!User.IsInRole("Admin"))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }
                else
                {
                    var theUser = userManager.FindByName(UserName);
                    var quotations = db.Quotations.Include(q => q.Category);
                    quotations = quotations.Where(q => q.User.Id == theUser.Id);
                    return View(quotations);
                }
            }
        }        

        // GET: /Quotation/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quotation quotation = db.Quotations.Find(id);
            if (quotation == null)
            {
                return HttpNotFound();
            }
            return View(quotation);
        }

        
        // GET: /Quotation/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name");
            return View();
        }

        public ActionResult AddCategory()
        {            
            return View(); 
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCategory(Category category)
        {
            if(ModelState.IsValid)
            {
                var check = db.Categories.Where(c => c.Name == category.Name);
                if (check.Count() == 0)
                {   
                    db.Categories.Add(category);
                    db.SaveChanges();
                    return RedirectToAction("Create");
                }
                else
                {
                    ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", category.CategoryID);
                    return View(category);
                }
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", category.CategoryID);
            return View(category);
        }

        // POST: /Quotation/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="QuotationID,CategoryID,Quote,Author,Date")] Quotation quotation)
        {
           var user = userManager.FindById(User.Identity.GetUserId());
           quotation.Date = DateTime.Now;
           quotation.User = user;
            if (ModelState.IsValid)
            {                
                db.Quotations.Add(quotation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", quotation.CategoryID);
            return View(quotation);
        }

        // GET: /Quotation/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quotation quotation = db.Quotations.Find(id);
            if (quotation == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", quotation.CategoryID);
            return View(quotation);
        }

         // POST: /Quotation/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="QuotationID,CategoryID,Quote,Author,Date")] Quotation quotation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(quotation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", quotation.CategoryID);
            return View(quotation);
        }

        // GET: /Quotation/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quotation quotation = db.Quotations.Find(id);
            if (quotation == null)
            {
                return HttpNotFound();
            }
            return View(quotation);
        }

        // POST: /Quotation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Quotation quotation = db.Quotations.Find(id);
            db.Quotations.Remove(quotation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Quotes/Views/Quotation/AddCategory.cshtml
@model Quotes.Models.Category

@{
    ViewBag.Title = "AddCategory";
}

<h2>AddCategory</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Create")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Quotes/Views/Quotation/Create.cshtml
@model Quotes.Models.Quotation

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Quotation</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "Category", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", String.Empty) @Html.ActionLink("Add New Category", "AddCategory")
                @Html.ValidationMessageFor(model => model.CategoryID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quote, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quote)
                @Html.ValidationMessageFor(model => model.Quote)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author)
                @Html.ValidationMessageFor(model => model.Author)
            </div>
        </div>
        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Quotes/Views/Quotation/Delete.cshtml
@model Quotes.Models.Quotation

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Quotation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quote)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quote)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Quotes/Views/Quotation/Details.cshtml
@model Quotes.Models.Quotation

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Quotation</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quote)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quote)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.QuotationID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Quotes/Views/Quotation/Edit.cshtml
@model Quotes.Models.Quotation

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Quotation</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.QuotationID)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", String.Empty)
                @Html.ValidationMessageFor(model => model.CategoryID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quote, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quote)
                @Html.ValidationMessageFor(model => model.Quote)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author)
                @Html.ValidationMessageFor(model => model.Author)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date)
                @Html.ValidationMessageFor(model => model.Date)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Quotes/Views/Quotation/Index.cshtml
@model IEnumerable<Quotes.Models.Quotation>


    @{
        ViewBag.Title = "Index";
    }

    <h2>Index</h2>

    @if (ViewBag.admin)
    {
         using (Html.BeginForm("userQuotes", "Quotation", FormMethod.Get))
         { 
            <p>
            @Html.DropDownList("UserName", "Select a User")
            <input type="submit" value="Get Quotes"/>
            </p>
         }

        <p>
            @Html.ActionLink("Admin Table", "adminIndex", "Admin")
        </p>

    }

    @if (ViewBag.loggedIn)
    {
        <p>
            @Html.ActionLink("My Quotes", "userQuotes")
        </p>
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
    }

    @using (Html.BeginForm())
    {
        <p>
            Search Quotes: @Html.TextBox("filter")
            <input type="submit" value="Search" />
        </p>
    }

    @using (Html.BeginForm())
    {
        if (ViewBag.ShowDisplayAllButton)
        {
            <input type="submit" value="Display All" />
        }
    }

    @using (Html.BeginForm())
    {
        if (ViewBag.ShowUnhideButton)
        {
            @Html.ActionLink("Unhide", "Unhide")
        }
    }


    @using GridMvc.Html
    @Html.Grid(Model).Columns(columns =>
{
    columns.Add(Quote => Quote.Category.Name).Titled("Category").Sortable(true).Filterable(true);
    columns.Add(Quote => Quote.Quote).Titled("Quote");
    columns.Add(Quote => Quote.Author).Titled("Author").Sortable(true).Filterable(true);
    columns.Add(Quote => Quote.Date).Titled("Date").Sortable(true).Filterable(true).Format("{0:MM/dd/yyyy}");
    columns.Add().Sanitized(false).Encoded(false).RenderValueAs(Quote => Html.ActionLink("Hide", "HideQuote", "Quotation", new { Id = Quote.QuotationID.ToString() }, null));

}).WithPaging(20)

Quotes/Views/Quotation/userQuotes.cshtml
@model IEnumerable<Quotes.Models.Quotation>

@{
    ViewBag.Title = "userQuotes";
}

<h2>userQuotes</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @Html.ActionLink("Return to Index", "Index")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quote)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quote)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Author)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.QuotationID }) |
            @Html.ActionLink("Details", "Details", new { id=item.QuotationID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.QuotationID })
        </td>
    </tr>
}

</table>